name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest

    name: Deno ${{ matrix.deno-version }}
    strategy:
      matrix:
        deno-version: ["v1.6", "v1.7", "nightly"]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Use Deno ${{ matrix.deno-version }}
      uses: denolib/setup-deno@v2
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Check demo.ts
      run: time deno cache demo.ts

    - name: Run tests
      run: time deno test --coverage --unstable --allow-net=localhost --allow-read=/proc/self
